### ISSUE TITLE
Winning test assumes last chip is endpoint

### ISSUE THREAD

**Issue by metaember** [metaember/games#1]
# Winning test assumes last chip is endpoint. 

## Example:

Consider the scenario:
`. . X X . X .`
Placing a chip in col 5 should result in a win.

**Comment by masatoshichang** [comment]
Possibly another example:
```
 | X O O O X O X |
 | O X X X O O O |
 | X O O O X X X |
 | O X X X O O O |
 | X O O O X O X |
 | O X X X X X O |
 | X O X O X O X |
```
