### ISSUE TITLE
Cascade behaviour

### ISSUE THREAD

**Issue by metaember** [metaember/games#25]
I'm not sure how the cascading reveal should work in this scenario:

```
Query ?c 0 0 

0 | . 1 #
1 | . 1 #
2 | . 1 #
    ------
    0 1 2
```

There is one mine, on `2,1`. Should `2,2`and `2,0` be automatically revealed when clicking say `0,0`?

**Comment by masatoshichang** [comment]
Seems like if you reveal those, then it will make it too easy to determine where the mine is.

**Comment by metaember** [comment]
Yeah I guess that makes sense. ty!
