### ISSUE TITLE
Read a list of words from a file

### ISSUE THREAD

**Issue by metaember** [metaember/games#6]
As reported by issue #5, hangman only has a few words in its repertoire. We should have a plaintext file containing a lot of words, and choose one at random to use.

**Comment by masatoshichang** [comment]
Added a function that reads a file of words. Would be good to add more words to the file.

**Comment by metaember** [comment]
We could use [this](https://github.com/dwyl/english-words). Also, we might consider filtering words that are too short, or implement difficulty settings.
